import { Geist, Urbanist } from "next/font/google";
import "./globals.css";
import NavBar from "./components/nav/NavBar";
import { AuthProvider } from "@/context/AuthContext";
import { SocketProvider } from "./context/SocketProvider";
import { LoaderProvider } from "./context/LoaderContext";
import { ToastProvider } from "./context/ToastProvider";
import { Providers } from "./context/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const urbanist = Urbanist({
  subsets: ["latin"],
  variable: "--font-urbanist",
});

export const metadata = {
  title: "Dev battle",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${urbanist.variable} flex flex-col min-h-screen scrollbar-custom`}>
        <ToastProvider/>
        <Providers>
          <LoaderProvider>
            <AuthProvider>
              <SocketProvider>
                <NavBar/>
                <main className="flex-1 h-full">{children}</main>
              </SocketProvider>
            </AuthProvider>
          </LoaderProvider>
        </Providers>
      </body>
    </html>
  );
}
